Improve QR page
kir-dev/cmsch pull request #151
Opened 2022-01-25 19:39 UTC by poiuztrewq1

A few improvements happened in this pr:
- removed todo text
- removed types from stamp
- improved spacing
- used common components like Loading, and ServiceContext throw error
- fixed a little bug in the common loading component
- improved the stamp colors, so they are more inline with the style of the page and better to look at in night mode

2022-01-25 19:41 UTC, poiuztrewq1 commented
Some questions: Should we handle token types on frontend? Like other icon on tokens with 'extra type' and/or exclude them from counting?

2022-01-25 20:32 UTC, Gerviba commented
> Some questions: Should we handle token types on frontend? Like other icon on tokens with 'extra type' and/or exclude them from counting?

We count the 'default' types as stamps, so for testing and other usage we might introduce another icon or a color, but it is not a feature request in any means.

2022-01-26 16:34 UTC, berenteb commented
`Error {name: "NoVideoInputDevicesError", message: "No video input devices found"}`

2022-01-26 16:44 UTC, berenteb requested changes
It is coming together, appreciate the spacing! Only a few things I noticed. I can't test the QR scan result, just imagined it from the code 😆

2022-01-26 16:44 UTC, berenteb commented on src/main/client/src/components/@pages/QRList.tsx
> +        A standoknál végzett aktív tevékenyégért QR kódokat lehet gyűjteni. Ha eleget összegíűjtesz, beválthatod egy tanköri jelenlétre.
Typoooo

2022-01-26 16:44 UTC, berenteb commented on src/main/client/src/components/@pages/QRList.tsx
> +      <Heading as="h3" mt="10">
Add size explicitly. There is no global size definitions for headings for some reasons. Add a lg or smth. Now it maatches size with h1.

2022-01-26 16:44 UTC, berenteb commented on src/main/client/src/components/@pages/QRScan.tsx
> +      <ButtonGroup alignSelf="center">
Easier to add margin top to the button group, not to the buttons individually.

2022-01-26 17:29 UTC, poiuztrewq1 commented
Apart from the requests there are some updates. 
* Cleaned up the states in the QRList page. (Added interface instead of many useState calls)
* Add different icon to the stamp, if its not a "default". So there will be no confusion why there isn't any progress
* Only count default stamps in the progress bar and info box

There are some pictures from the scan page for those who can't run the backend:
![Screen Shot 2022-01-26 at 18 25 21](https://user-images.githubusercontent.com/25415958/151215188-94b0e8ca-2843-41a7-af35-681192f827ae.png)
![Screen Shot 2022-01-26 at 18 24 29](https://user-images.githubusercontent.com/25415958/151215194-cffb82c1-eaa3-4cb0-b515-d338856d749b.png)

2022-01-26 22:35 UTC, berenteb approved these changes
Thank you! Also these pictures helped a lot, looks amazing!

2022-01-26 22:35 UTC, merged