Feature/live event
kir-dev/cmsch pull request #640
Opened 2023-10-04 16:24 UTC by FearsomeRover

Valami ilyesmire gondolt a költő? 123.issue a táblázatban, annak is a 2.fele.

2023-10-04 17:12 UTC, Tschonti commented
Nem én voltam a költő, de szerintem igen :D az esemény neve lehetne még link, illetve érdemes lenne kipróbálni, hogy az <EventIndicator /> nem nézne-e ki jól itt.
Ja és a fájlnév mindig egyezzen meg a komponens nevével. Most különösen zavaró, mert van másik CurrentEvent.tsx is.

2023-10-04 18:02 UTC, FearsomeRover commented
Pont azért írtam át a functiont, mert volt egy másik ilyen nevű, csak a filet elfelejtettem. Köszi

2023-10-05 15:42 UTC, Tschonti requested changes
very cool, just one more thing

2023-10-05 15:42 UTC, Tschonti commented on frontend/src/common-components/CurrentEventCard.tsx
> +    >
egy `alignItems="center" még jól jön ide

2023-10-05 15:42 UTC, Tschonti commented on frontend/src/common-components/CurrentEventCard.tsx
> +  //)
ezek véletlen maradtak itt?

2023-10-05 16:51 UTC, Tschonti approved these changes

2023-10-05 22:10 UTC, merged