Update workflows for new git flow
kir-dev/cmsch pull request #814
Opened 2024-10-07 17:50 UTC by albi005

2024-10-08 18:50 UTC, Isti01 requested changes
This system is better than the previous one imho, but the current deploy config on Vercel uses the old structure too, could you update that too?

2024-10-08 18:51 UTC, Isti01 commented
Also, what do you think, about this? @berenteb @triszt4n @Gerviba

2024-10-08 19:30 UTC, albi005 commented
@Isti01 Do we want to deploy
1. on every push to main,
2. manually,
3. or on new tags?

2025-01-08 23:12 UTC, albi005 commented
Superseded by https://github.com/kir-dev/cmsch/pull/845 and https://github.com/kir-dev/cmsch/pull/846

- don't want to update the code when deploying a new instance
- don't want to rename branches

2025-01-08 23:12 UTC, closed without merging