Bucketlist API implementation
kir-dev/cmsch pull request #83
Opened 2022-01-19 12:35 UTC by Tschonti

I think this should work, but I couldn't test it properly because the API calls to /achievement respond with almost no data (as if there were no categories or achievements), even though I can see mock data in the admin.  Is that feature not ready on the backend or did I set up the backend incorrectly? There are also some styling changes to be made.

2022-01-19 16:36 UTC, triszt4n reviewed
I guess there are no mocked data in the database yet, if you are interested in the Kotlin language, you could take a look at the `TestConfig.kt` file, where the mocked data is created. Otherwise you might be missing the `local,test` Spring profiles from your run config. Spring is a "natural" part of the Ultimate version of IntelliJ IDEA, you should take installing it into consideration (use your @sch.bme.hu account for free Student licence)

2022-01-19 21:15 UTC, Tschonti commented
ooh no I messed something up with git

2022-01-19 21:46 UTC, berenteb requested changes
One minor thing.
I can't get this to work, might be a backend related problem or I missed a setting. I get an empty category even with categories added on the admin panel. Also, you are showing a skeleton even if an empty array of achievements is returned. This is misleading, I suggest writiong out a message for that.

2022-01-19 21:46 UTC, berenteb commented on src/main/client/src/components/@pages/AchievementPage.tsx
> +        <Heading marginBottom="0px">{achDetails.achievement?.title}</Heading>
marginBottom={0}

2022-01-19 21:53 UTC, Tschonti commented
You need to be REALLY logged in to make it work 😃 What worked for me is this:
You launch the app, delete the cookies, log in to the admin, give yourself a group (tankör), delete the cookies again, log in again and it'll work

2022-01-19 22:37 UTC, berenteb commented
Oh yeah right, the individual bucketlist was not available! Will look into it tomorrow.

2022-01-19 23:32 UTC, triszt4n commented
> ooh no I messed something up with git

Let's look into this problem in the afternoon, contact me on Slack thx

2022-01-20 00:00 UTC, triszt4n commented on src/main/client/src/components/@pages/AchievementPage.tsx
> +        <Heading marginBottom="0px">{achDetails.achievement?.title}</Heading>
Shorthand: `mb={0}`

2022-01-20 12:39 UTC, berenteb commented
> > ooh no I messed something up with git
> 
> Let's look into this problem in the afternoon, contact me on Slack thx
I need help to test out the feature, please contact me about this meeting!

2022-01-20 21:51 UTC, triszt4n commented
Did the rebase, as the #97 test was successful (all files remained intact after the rebasing, functionality is same)

2022-01-21 17:22 UTC, triszt4n approved these changes

2022-01-21 17:23 UTC, triszt4n commented
@Tschonti is still designing the UI, so don't merge yet

2022-01-21 17:52 UTC, Tschonti commented
Rebased to the current master, so now it can be tested with authContext. File upload size limit is 1 MB in development.

2022-01-21 18:40 UTC, berenteb approved these changes

2022-01-21 18:47 UTC, merged